image: "rsampaio/alpine-elixir:latest"
services:
  - "postgres"

variables:
  POSTGRES_DB: infrapi_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  MIX_ENV: test

before_script:
  - cp config/test.exs.ci config/test.exs
  - mix deps.get
  - mix ecto.create
  - mix ecto.migrate

stages:
  - test

job:
  stage: test
  script:
    - mix test
  cache:
    paths:
      - "_build"
      - "deps"
